[CHK-706] presa in carico
pagopa/pagopa-checkout-fe pull request #155
Opened 2023-01-10 14:31 UTC by ciuffagianluca

When the result from nodo for a payment is a timeout and the payment is taken in charge, the outcome is ok, but the payment result is not still available, for a better user experience the result page should show a coherent message for this situation

#### List of Changes

Added new type of outcome
Evaluation of id status to check this OK peculiar result
Update translation

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-01-10 14:35 UTC, giovanniberti approved these changes

2023-01-10 14:35 UTC, giovanniberti commented on src/utils/transactions/TransactionResultUtil.ts
> +  TAKE_IN_CHARGE = "15",
[bikeshedding]
What about
```suggestion
  TAKEN_IN_CHARGE = "15",
```
?

2023-01-10 14:35 UTC, giovanniberti commented on src/utils/transactions/TransactionResultUtil.ts
> +  TAKE_IN_CHARGE = "15",
(see above)

2023-01-10 14:35 UTC, giovanniberti commented
🚀

2023-01-10 17:39 UTC, ciuffagianluca commented on src/utils/transactions/TransactionResultUtil.ts
> +  TAKE_IN_CHARGE = "15",
That's reasonable

2023-01-10 17:40 UTC, ciuffagianluca commented on src/utils/transactions/TransactionResultUtil.ts
> +  TAKE_IN_CHARGE = "15",
That's reasonable

2023-01-11 12:30 UTC, infantesimone requested changes
this PR have to go into prod before ecommerce?

2023-01-11 12:30 UTC, infantesimone commented on src/utils/transactions/TransactionResultUtil.ts
> +      outcomeEnum === OutcomeEnum.SUCCESS && idStatus === 14
are we sure that the state to consider is 14?

2023-01-30 10:56 UTC, closed without merging