[CHK-2622] use card remote icon
pagopa/pagopa-checkout-fe pull request #327
Opened 2024-03-25 13:27 UTC by ciuffagianluca

Use card remote icon

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-25 15:46 UTC, mmoio requested changes

2024-03-25 15:46 UTC, mmoio commented on src/features/payment/components/PaymentChoice/PaymentMethod.tsx
> -      <CreditCardIcon color="primary" fontSize="small" />
The import of this component, on line 11, should be removed

2024-03-25 15:46 UTC, mmoio commented on src/features/payment/components/PaymentChoice/PaymentMethod.tsx
> -    method.paymentTypeCode === PaymentCodeTypeEnum.CP ? (
PaymentCodeTypeEnum import, on line 14, should be removed

2024-03-25 15:50 UTC, mmoio commented
Could you also add a description and a screenshot please?

2024-03-26 14:16 UTC, mmoio approved these changes

2024-03-27 08:19 UTC, pietro-tota approved these changes

2024-03-27 08:48 UTC, merged